### ISSUE TITLE
1.14.1

### ISSUE THREAD

**Issue by poboy975** [abused/AbusedLib#2]
Hi, I just updated to your latest builds, and I keep getting a crash. Here is the crash report from multimc.

`MultiMC version: 0.6.5-1302

Minecraft folder is:
C:/Users/durlo/Downloads/MultiMC/instances/Fabric 1.14.1/.minecraft

Java path is:
C:/Program Files/Java/jdk1.8.0_144/bin/javaw.exe

Java is version 1.8.0_144, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  C:/Users/durlo/Downloads/MultiMC/instances/Fabric 1.14.1/natives

Traits:
traits FirstThreadOnMacOS

Libraries:
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/realms/1.14.15/realms-1.14.15.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader/0.4.7+build.147/fabric-loader-0.4.7+build.147.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/yarn/1.14.1+build.5/yarn-1.14.1+build.5.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.1.1.8/tiny-mappings-parser-0.1.1.8.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/tiny-remapper/0.1.0.33/tiny-remapper-0.1.0.33.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/ow2/asm/asm/7.1/asm-7.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/ow2/asm/asm-analysis/7.1/asm-analysis-7.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/ow2/asm/asm-commons/7.1/asm-commons-7.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/ow2/asm/asm-tree/7.1/asm-tree-7.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/ow2/asm/asm-util/7.1/asm-util-7.1.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/minecraft/1.14.1/minecraft-1.14.1-client.jar

Native libraries:
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1-natives-windows.jar
  C:/Users/durlo/Downloads/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  AbusedLib-1.0.2
  AnimalNet-1.8.2+Fabric+1.14
  antiqueatlas-5.0.2-fabric
  ArcaneMagic-1.0.0-beta3
  beach-slimes-1.2.0+mc1.14.1
  betterutilities-1.4.0
  blockmeter-1.0.0
  Cardinal-Components-API-1.1.0
  Cardinal-Energy-1.0.1
  chunk-activator-1.1.0+mc1.14.1
  ClothConfig-0.2.1.14
  composable-automation-0.4.0+mc1.14.1
  crochet-1.0.2
  desire-paths-1.2.0
  Disenchanting-0.8.1+mc1.14.1
  easyexcavate-1.5.1
  epicurean-gastronomy-2.2.0+1.14.1
  fabric-api-0.3.0-pre+build.157a
  fabric-language-kotlin-1.3.30+build.2
  FabricMagnet-1.14-1.0.1
  glassential-fabric-1.14-1.0.0
  Harvest-1.14-fabric-1.0.4
  Hwyla-fabric-1.14-1.9.16-60(1)
  illuminations-0.1.6-1.14.1
  leaf-decay-1.0.2
  LeatherCows-1.0.0.21-universal
  libblockattributes-0.4.0
  mappy-0.0.12a
  miners-horizon-1.4.0
  mousewheelie-1.1.12+1.14.2+Pre-Release+2
  preview_OptiFine_1.14_HD_U_F1_pre2
  RefinedMachinery-1.0.2
  Retro-Exchange-1.14-2.2.1
  RoughlyEnoughItems-2.9.112
  sodden-1.0.1.2
  SoulShards-fabric-1.14.1-1.0.7-9
  stockpile-1.0.4+1.14.1
  SuperOres-2.0.1
  vanilla-hammers-1.3.2
  VoxelMap-1.9.2_for_1.14(.1)
  wool-1.3.6-1.14.1

Params:
  --username  --version MultiMC5 --gameDir C:/Users/durlo/Downloads/MultiMC/instances/Fabric 1.14.1/.minecraft --assetsDir C:/Users/durlo/Downloads/MultiMC/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:+UseG1GC, -Dsun.rmi.dgc.server.gcInterval=2147483646, -XX:+UnlockExperimentalVMOptions, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=25, -XX:G1HeapRegionSize=32M, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms2048m, -Xmx8192m, -Duser.language=en]

Minecraft process ID: 23748

Using onesix launcher.

[19:26:18] [main/INFO]: Loading for game Minecraft 1.14.1
[19:26:18] [ForkJoinPool-1-worker-3/WARN]: Mod ID animalnet uses outdated schema version: 0 < 1
[19:26:18] [ForkJoinPool-1-worker-4/WARN]: Mod ID fabric uses outdated schema version: 0 < 1
[19:26:18] [ForkJoinPool-1-worker-3/WARN]: Mod ID fmagnet uses outdated schema version: 0 < 1
[19:26:21] [ForkJoinPool-1-worker-6/WARN]: Mod ID harvest uses outdated schema version: 0 < 1
[19:26:21] [ForkJoinPool-1-worker-2/WARN]: Mod ID illuminations uses outdated schema version: 0 < 1
[19:26:21] [main/INFO]: [FabricLoader] Loading 70 mods: fabric-keybindings-v0@0.1.0+f1618918, wool@1.3.6-1.14.1, animalnet@1.8.2 Fabric 1.14, desire-paths@1.2.0, fabricloader@0.4.7+build.147, leaf-decay@1.0.2, cotton@0.6.6+1.14.1-SNAPSHOT, vanilla-hammers@1.3.2, sodden@1.0.1.2, fabric-containers-v0@0.1.0+f1618918, fmagnet@${version}, multiblockapi@1.0.1-1, miners_horizon@1.4.0, glassential@1.14-1.0.0, fabric-api-base@0.1.0+f1618918, libblockattributes@0.4.0, cutsceneapi@1.0.0-beta5, fabric-keybindings@0.1.0+93af775a, chunkactivator@1.1.0+mc1.14.1, fabric-textures-v0@0.1.0+f1618918, autoconfig1@1.1.0+mc1.14.1, waila@1.9.16, abusedlib@1.0.2, leathercows@1.0.0, fabric@0.3.0-pre+build.157a, epicurean@2.2.0+1.14.1, fabric-networking-v0@0.1.1+57f0d19c, antiqueatlas@5.0.2-fabric, arcanemagic@1.0.0-beta3, beachslimes@1.2.0+mc1.14.1, cloth@0.3.1+build.23, fabric-networking-blockentity-v0@0.1.0+f1618918, cardinalenergy@1.0.1, illuminations@0.1.6, refinedmachinery@1.0.2, betterutilities@1.4.0, mappy@0.0.12a, cardinal_components@1.1.0, retroexchange@1.0.0, soulshards@1.0.8, fabric-crash-report-info-v1@0.1.0+f1618918, fabric-events-interaction-v0@0.1.0+f1618918, roughlyenoughitems@2.9+build.112, fabric-language-kotlin@1.3.30+build.2, fabric-rendering-v0@0.1.0+f1618918, mousewheelie@1.1.12+1.14.2 Pre-Release 2, silk@1.2.4-43, fabric-resource-loader-v0@0.1.1+eff4f58d, harvest@1.0.4, fabric-resource-loader@0.1.0+93af775a, fabric-content-registries-v0@0.1.1+45e1a1c8, fabric-tag-extensions-v0@0.1.0+f1618918, crochet@1.0.2, stockpile@1.0.4+1.14.1, fabric-commands-v0@0.1.0+f1618918, fabric-registry-sync-v0@0.1.0+f1618918, cloth-config@0.2.1+build.14, blockmeter@1.0.0, fabric-mining-levels-v0@0.1.0+f1618918, composableautomation@0.4.0+mc1.14.1, fabric-tag-hooks@0.1.0+93af775a, voxelmap@1.9.2, fabric-events-lifecycle-v0@0.1.0+9232ac87, disenchanting@0.8.1, fabric-item-groups-v0@0.1.0+f1618918, fabric-models-v0@0.1.0+f1618918, superores@2.0.1, fabric-object-builders-v0@0.1.0+9232ac87, easyexcavate@1.5.1, tweed@2.1.0-beta.5
[19:26:21] [main/WARN]: Mod `animalnet` (1.8.2 Fabric 1.14) does not respect SemVer - comparison support is limited.
[19:26:21] [main/WARN]: Mod `sodden` (1.0.1.2) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[19:26:21] [main/WARN]: Mod `fmagnet` (${version}) does not respect SemVer - comparison support is limited.
[19:26:21] [main/WARN]: Mod `mappy` (0.0.12a) does not respect SemVer - comparison support is limited.
[19:26:21] [main/WARN]: Mod `mousewheelie` (1.1.12+1.14.2 Pre-Release 2) does not respect SemVer - comparison support is limited.
[19:26:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/durlo/Downloads/MultiMC/libraries/net/fabricmc/sponge-mixin/0.7.11.30/sponge-mixin-0.7.11.30.jar Service=Knot/Fabric Env=CLIENT
[19:26:22] [main/INFO]: Compatibility level set to JAVA_8
[19:26:22] [main/WARN]: Mixin config fabric-networking-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config refinedmachinery.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config wool.common.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config tweed.client.mixin.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config easyexcavate.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config mixins.retroexchange.common.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-rendering-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
[19:26:22] [main/WARN]: Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-commands-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-mining-levels-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-resource-loader.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config leathercows.common.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-textures-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config blockmeter.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-models-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-keybindings-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config antiqueatlasoverlay.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-events-lifecycle-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config superores.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config modid.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config soulshards.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config cotton.common.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config desire-paths.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config antiqueatlas.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config minershorizon.common.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config hwyla.client.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config minershorizon.client.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config betterutilities.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config abusedlib.mixins.json does not specify "minVersion" property
[19:26:23] [main/WARN]: Mixin config fabric-keybindings.mixins.json does not specify "minVersion" property
[19:26:24] [main/INFO]: Setting user: poboy975
[19:26:27] [main/ERROR]: Missing translations: item.minecraft.air
[19:26:29] [main/INFO]: [34m[COTTON]: [0m[0mLoaded config.[0m
[19:26:29] [main/INFO]: [Cutscene API] Hello there
[19:26:29] [main/INFO]: Discovered plugin desire-paths:waila_support provided by desire-paths at com.matjojo.desire_paths.wailaSupport.WailaPlugin
[19:26:29] [main/INFO]: Discovered plugin waila:core provided by waila at mcp.mobius.waila.addons.core.PluginCore
[19:26:29] [main/INFO]: Discovered plugin waila:vanilla provided by waila at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[19:26:29] [main/INFO]: Discovered plugin soulshards provided by soulshards at info.tehnut.soulshards.compat.waila.SoulShardsWailaPlugin
[19:26:29] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.core.PluginCore
[19:26:29] [main/INFO]: Registering plugin at mcp.mobius.waila.addons.minecraft.PluginMinecraft
[19:26:29] [main/INFO]: Registering plugin at com.matjojo.desire_paths.wailaSupport.WailaPlugin
[19:26:29] [main/INFO]: Registering plugin at info.tehnut.soulshards.compat.waila.SoulShardsWailaPlugin
[19:26:29] [main/INFO]: [LeatherCows] Loading!
[19:26:33] [main/INFO]: Loading config file refinedmachinery/config.json
[19:26:33] [main/INFO]: Loaded Ore Generation Config for Refined Machinery
[19:26:35] [main/INFO]: [STDOUT]: Hello World!
[19:26:35] [main/INFO]: [Disenchanting] Initializing Disenchanting
[19:26:35] [main/INFO]: [STDOUT]: [EasyExcavate] Config loaded!
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/21/19 7:26 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoSuchMethodError: net.minecraft.class_2591$class_2592.method_11035(Ljava/util/function/Supplier;)Lnet/minecraft/class_2591$class_2592;
		at abused_master.abusedlib.registry.RegistryHelper.registerTile(RegistryHelper.java:59)
		at abused_master.abusedlib.AbusedLib.onInitialize(AbusedLib.java:20)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more
	Suppressed: java.lang.NoSuchMethodError: net.minecraft.class_2591$class_2592.method_11035(Ljava/util/function/Supplier;)Lnet/minecraft/class_2591$class_2592;
		at abused_master.abusedlib.registry.RegistryHelper.registerTile(RegistryHelper.java:59)
		at abused_master.refinedmachinery.registry.ModBlockEntities.registerBlockEntities(ModBlockEntities.java:52)
		at abused_master.refinedmachinery.RefinedMachinery.onInitialize(RefinedMachinery.java:43)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.14.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4002590728 bytes (3817 MB) / 6006243328 bytes (5728 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=25 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8192m
	Fabric Mods: 
		abusedlib: AbusedLib 1.0.2
		animalnet: MrMarnic's AnimalNet 1.8.2 Fabric 1.14
		antiqueatlas: Antique Atlas 5.0.2-fabric
		arcanemagic: Arcane Magic 1.0.0-beta3
		autoconfig1: Auto Config v1 1.1.0+mc1.14.1
		beachslimes: Beach Slimes 1.2.0+mc1.14.1
		betterutilities: Better Utilities 1.4.0
		blockmeter: Block Meter 1.0.0
		cardinal_components: Cardinal Components API 1.1.0
		cardinalenergy: Cardinal Energy 1.0.1
		chunkactivator: Chunk Activator 1.1.0+mc1.14.1
		cloth: Cloth Events 0.3.1+build.23
		cloth-config: Cloth Config 0.2.1+build.14
		composableautomation: Composable Automation 0.4.0+mc1.14.1
		cotton: Cotton 0.6.6+1.14.1-SNAPSHOT
		crochet: Crochet 1.0.2
		cutsceneapi: Cutscene API 1.0.0-beta5
		desire-paths: Desire Paths 1.2.0
		disenchanting: Disenchanting 0.8.1
		easyexcavate: Easy Excavate 1.5.1
		epicurean: Epicurean Gastronomy 2.2.0+1.14.1
		fabric: Fabric API 0.3.0-pre+build.157a
		fabric-api-base: fabric-api-base 0.1.0+f1618918
		fabric-commands-v0: fabric-commands-v0 0.1.0+f1618918
		fabric-containers-v0: fabric-containers-v0 0.1.0+f1618918
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+f1618918
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+f1618918
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+9232ac87
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f1618918
		fabric-keybindings: fabric-keybindings 0.1.0+93af775a
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+f1618918
		fabric-language-kotlin: Fabric Language Kotlin 1.3.30+build.2
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+f1618918
		fabric-models-v0: fabric-models-v0 0.1.0+f1618918
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.0+f1618918
		fabric-networking-v0: fabric-networking-v0 0.1.1+57f0d19c
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.0+9232ac87
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.1.0+f1618918
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+f1618918
		fabric-resource-loader: fabric-resource-loader 0.1.0+93af775a
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+eff4f58d
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+f1618918
		fabric-tag-hooks: fabric-tag-hooks 0.1.0+93af775a
		fabric-textures-v0: fabric-textures-v0 0.1.0+f1618918
		fabricloader: Fabric Loader 0.4.7+build.147
		fmagnet: Fabric Magnet ${version}
		glassential: Glassential 1.14-1.0.0
		harvest: Harvest 1.0.4
		illuminations: Illuminations 0.1.6
		leaf-decay: Leaf Decay 1.0.2
		leathercows: Leather Cows 1.0.0
		libblockattributes: LibBlockAttributes 0.4.0
		mappy: Mappy 0.0.12a
		miners_horizon: Miner's Horizon 1.4.0
		mousewheelie: Mouse Wheelie 1.1.12+1.14.2 Pre-Release 2
		multiblockapi: MultiBlock API 1.0.1-1
		refinedmachinery: Refined Machinery 1.0.2
		retroexchange: Retro Exchange 1.0.0
		roughlyenoughitems: Roughly Enough Items 2.9+build.112
		silk: Silk API 1.2.4-43
		sodden: Sodden 1.0.1.2
		soulshards: Soul Shards Respawn 1.0.8
		stockpile: Stockpile 1.0.4+1.14.1
		superores: Super Ores 2.0.1
		tweed: Tweed API 2.1.0-beta.5
		vanilla-hammers: Vanilla Hammers 1.3.2
		voxelmap: VoxelMap 1.9.2
		waila: Hwyla 1.9.16
		wool: Wool 1.3.6-1.14.1
	Launched Version: MultiMC5
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\durlo\Downloads\MultiMC\instances\Fabric 1.14.1\.minecraft\crash-reports\crash-2019-05-21_19.26.35-client.txt
Process exited with code -1.
Clipboard copy at: 21 May 2019 19:27:27 -0500
`

**Comment by alothmanmoe** [comment]
Hey, the reason you crash is because the mods atm are only 1.14 not 1.14.1, I need to update them later today

**Comment by poboy975** [comment]
Oh, sorry. I saw that they updated recently and didn't check the mod version.

Thanks

Durlon Bryant
Cell: 224-639-0117

________________________________

**Comment by alothmanmoe** [comment]
Refined Machinery has updated to 1.14.2
